"""create domain schema

Revision ID: 5bd72efdd0ea
Revises:
Create Date: 2026-08-01 16:46:46.157821
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5bd72efdd0ea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=False),
        sa.Column("starting_year", sa.Integer(), nullable=False),
        sa.Column("starting_age", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("occupation", sa.String(length=200), nullable=False),
        sa.Column("education", sa.Text(), nullable=False),
        sa.Column("biography", sa.Text(), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("weaknesses", sa.JSON(), nullable=False),
        sa.Column("interests", sa.JSON(), nullable=False),
        sa.Column("goals", sa.JSON(), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("starting_stats", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("birth_year > 1900", name=op.f("ck_person_profiles_birth_year_valid")),
        sa.CheckConstraint(
            "starting_age >= 0", name=op.f("ck_person_profiles_starting_age_nonnegative")
        ),
        sa.CheckConstraint(
            "starting_year >= birth_year", name=op.f("ck_person_profiles_starting_year_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_profiles")),
    )
    op.create_index(op.f("ix_person_profiles_name"), "person_profiles", ["name"], unique=False)
    op.create_table(
        "scenarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("decision_question", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("number_of_universes", sa.Integer(), nullable=False),
        sa.Column(
            "simulation_mode",
            sa.Enum(
                "realistic",
                "cinematic",
                "utopian",
                "dark",
                "chaos",
                name="simulation_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "number_of_universes > 0", name=op.f("ck_scenarios_universe_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["person_profiles.id"],
            name=op.f("fk_scenarios_profile_id_person_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
    )
    op.create_index(op.f("ix_scenarios_profile_id"), "scenarios", ["profile_id"], unique=False)
    op.create_table(
        "universes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("subtitle", sa.String(length=220), nullable=False),
        sa.Column("premise", sa.Text(), nullable=False),
        sa.Column("visual_theme", sa.JSON(), nullable=False),
        sa.Column("starting_direction", sa.Text(), nullable=False),
        sa.Column("current_year", sa.Integer(), nullable=False),
        sa.Column("current_age", sa.Integer(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "blocked",
                "completed",
                "archived",
                name="universe_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_age >= 0", name=op.f("ck_universes_current_age_nonnegative")),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_universes_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universes")),
        sa.UniqueConstraint("scenario_id", "slug", name="uq_universes_scenario_slug"),
    )
    op.create_index(op.f("ix_universes_scenario_id"), "universes", ["scenario_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("universe_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "career",
                "education",
                "finance",
                "research",
                "startup",
                "health",
                "relationship",
                "social",
                "travel",
                "opportunity",
                "crisis",
                "random",
                "crossover",
                name="event_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Enum(
                "routine",
                "notable",
                "major",
                name="event_importance",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "narrative",
                "decision",
                "milestone",
                name="event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "resolved",
                name="event_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_generated", sa.Boolean(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "seeded",
                "system",
                "mock",
                "openai",
                name="event_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("importance != ''", name=op.f("ck_events_importance_present")),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["universes.id"],
            name=op.f("fk_events_universe_id_universes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_universe_id"), "events", ["universe_id"], unique=False)
    op.create_index(op.f("ix_events_year"), "events", ["year"], unique=False)
    op.create_table(
        "future_self_conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("universe_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("future_self_age", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "future_self_age >= 0",
            name=op.f("ck_future_self_conversations_future_self_age_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["universes.id"],
            name=op.f("fk_future_self_conversations_universe_id_universes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_future_self_conversations")),
    )
    op.create_index(
        op.f("ix_future_self_conversations_universe_id"),
        "future_self_conversations",
        ["universe_id"],
        unique=False,
    )
    op.create_table(
        "life_state_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("universe_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("career_title", sa.String(length=200), nullable=False),
        sa.Column("career_level", sa.Integer(), nullable=False),
        sa.Column("monthly_income_eur", sa.Integer(), nullable=False),
        sa.Column("net_worth_eur", sa.Integer(), nullable=False),
        sa.Column("health", sa.Integer(), nullable=False),
        sa.Column("relationships", sa.Integer(), nullable=False),
        sa.Column("research_impact", sa.Integer(), nullable=False),
        sa.Column("reputation", sa.Integer(), nullable=False),
        sa.Column("freedom", sa.Integer(), nullable=False),
        sa.Column("stress", sa.Integer(), nullable=False),
        sa.Column("happiness", sa.Integer(), nullable=False),
        sa.Column("discipline", sa.Integer(), nullable=False),
        sa.Column("creativity", sa.Integer(), nullable=False),
        sa.Column("chaos", sa.Integer(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("active_flags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("age >= 0", name=op.f("ck_life_state_snapshots_age_nonnegative")),
        sa.CheckConstraint(
            "career_level BETWEEN 0 AND 100",
            name=op.f("ck_life_state_snapshots_career_level_range"),
        ),
        sa.CheckConstraint(
            "chaos BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_chaos_range")
        ),
        sa.CheckConstraint(
            "creativity BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_creativity_range")
        ),
        sa.CheckConstraint(
            "discipline BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_discipline_range")
        ),
        sa.CheckConstraint(
            "freedom BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_freedom_range")
        ),
        sa.CheckConstraint(
            "happiness BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_happiness_range")
        ),
        sa.CheckConstraint(
            "health BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_health_range")
        ),
        sa.CheckConstraint(
            "monthly_income_eur >= 0",
            name=op.f("ck_life_state_snapshots_monthly_income_nonnegative"),
        ),
        sa.CheckConstraint(
            "relationships BETWEEN 0 AND 100",
            name=op.f("ck_life_state_snapshots_relationships_range"),
        ),
        sa.CheckConstraint(
            "reputation BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_reputation_range")
        ),
        sa.CheckConstraint(
            "research_impact BETWEEN 0 AND 100",
            name=op.f("ck_life_state_snapshots_research_impact_range"),
        ),
        sa.CheckConstraint(
            "stress BETWEEN 0 AND 100", name=op.f("ck_life_state_snapshots_stress_range")
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["universes.id"],
            name=op.f("fk_life_state_snapshots_universe_id_universes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_life_state_snapshots")),
        sa.UniqueConstraint("universe_id", "year", name="uq_snapshots_universe_year"),
    )
    op.create_index(
        op.f("ix_life_state_snapshots_universe_id"),
        "life_state_snapshots",
        ["universe_id"],
        unique=False,
    )
    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            """
            CREATE TRIGGER prevent_life_state_snapshot_updates
            BEFORE UPDATE ON life_state_snapshots
            BEGIN
                SELECT RAISE(ABORT, 'life-state snapshots are immutable');
            END
            """
        )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("universe_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "artifact_type",
            sa.Enum(
                "news_article",
                "diary_entry",
                "linkedin_update",
                "academic_abstract",
                "company_announcement",
                "email",
                "text_conversation",
                "conference_invitation",
                "rejection_letter",
                "award",
                "financial_snapshot",
                "calendar_entry",
                "social_media_post",
                "future_self_note",
                name="artifact_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_artifacts_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["universes.id"],
            name=op.f("fk_artifacts_universe_id_universes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(op.f("ix_artifacts_event_id"), "artifacts", ["event_id"], unique=False)
    op.create_index(op.f("ix_artifacts_universe_id"), "artifacts", ["universe_id"], unique=False)
    op.create_index(op.f("ix_artifacts_year"), "artifacts", ["year"], unique=False)
    op.create_table(
        "choices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("immediate_effects", sa.JSON(), nullable=False),
        sa.Column("delayed_effects", sa.JSON(), nullable=False),
        sa.Column("requirements", sa.JSON(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="risk_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_choices_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_choices")),
        sa.UniqueConstraint("event_id", "label", name="uq_choices_event_label"),
    )
    op.create_index(op.f("ix_choices_event_id"), "choices", ["event_id"], unique=False)
    op.create_index(
        "uq_choices_one_selected_per_event",
        "choices",
        ["event_id"],
        unique=True,
        sqlite_where=sa.text("selected IS 1"),
    )
    op.create_table(
        "future_self_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user",
                "future_self",
                "system",
                name="message_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("state_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["future_self_conversations.id"],
            name=op.f("fk_future_self_messages_conversation_id_future_self_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["state_snapshot_id"],
            ["life_state_snapshots.id"],
            name=op.f("fk_future_self_messages_state_snapshot_id_life_state_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_future_self_messages")),
    )
    op.create_index(
        op.f("ix_future_self_messages_conversation_id"),
        "future_self_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_future_self_messages_state_snapshot_id"),
        "future_self_messages",
        ["state_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "delayed_effects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("universe_id", sa.Uuid(), nullable=False),
        sa.Column("source_choice_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_year", sa.Integer(), nullable=False),
        sa.Column("effects", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_choice_id"],
            ["choices.id"],
            name=op.f("fk_delayed_effects_source_choice_id_choices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"],
            ["universes.id"],
            name=op.f("fk_delayed_effects_universe_id_universes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delayed_effects")),
    )
    op.create_index(
        op.f("ix_delayed_effects_source_choice_id"),
        "delayed_effects",
        ["source_choice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_delayed_effects_trigger_year"), "delayed_effects", ["trigger_year"], unique=False
    )
    op.create_index(
        op.f("ix_delayed_effects_universe_id"), "delayed_effects", ["universe_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delayed_effects_universe_id"), table_name="delayed_effects")
    op.drop_index(op.f("ix_delayed_effects_trigger_year"), table_name="delayed_effects")
    op.drop_index(op.f("ix_delayed_effects_source_choice_id"), table_name="delayed_effects")
    op.drop_table("delayed_effects")
    op.drop_index(
        op.f("ix_future_self_messages_state_snapshot_id"), table_name="future_self_messages"
    )
    op.drop_index(
        op.f("ix_future_self_messages_conversation_id"), table_name="future_self_messages"
    )
    op.drop_table("future_self_messages")
    op.drop_index(
        "uq_choices_one_selected_per_event",
        table_name="choices",
        sqlite_where=sa.text("selected IS 1"),
    )
    op.drop_index(op.f("ix_choices_event_id"), table_name="choices")
    op.drop_table("choices")
    op.drop_index(op.f("ix_artifacts_year"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_universe_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_event_id"), table_name="artifacts")
    op.drop_table("artifacts")
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS prevent_life_state_snapshot_updates")
    op.drop_index(op.f("ix_life_state_snapshots_universe_id"), table_name="life_state_snapshots")
    op.drop_table("life_state_snapshots")
    op.drop_index(
        op.f("ix_future_self_conversations_universe_id"), table_name="future_self_conversations"
    )
    op.drop_table("future_self_conversations")
    op.drop_index(op.f("ix_events_year"), table_name="events")
    op.drop_index(op.f("ix_events_universe_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_universes_scenario_id"), table_name="universes")
    op.drop_table("universes")
    op.drop_index(op.f("ix_scenarios_profile_id"), table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_index(op.f("ix_person_profiles_name"), table_name="person_profiles")
    op.drop_table("person_profiles")
    # ### end Alembic commands ###
